baseURL = 'https://rebma.io/'
languageCode = 'en-us'
title = 'rebma.io'
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "rebma"
  showLanguageSelector = false
  autoCover = true
  showLastUpdated = true
  enableGitInfo = true
  readingTime = true

[languages]
  [languages.en]
    [languages.en.params.logo]
      logoText = "rebma.io"
      logoHomeLink = "/"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/rebma-io/"